# Generated by Django 5.1.7 on 2025-05-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='privacy_url',
            field=models.URLField(blank=True, null=True, verbose_name='Privacy Policy URL'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='terms_url',
            field=models.URLField(blank=True, null=True, verbose_name='Terms & Conditions URL'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
