# Generated by Django 5.1.7 on 2025-05-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_contactinfo_facebook_contactinfo_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='privacy_url',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='terms_url',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='twitter',
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_url', models.URLField(blank=True, null=True, verbose_name='Terms & Conditions URL')),
                ('privacy_url', models.URLField(blank=True, null=True, verbose_name='Privacy Policy URL')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_pages', to='accounts.contactinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='accounts.contactinfo')),
            ],
        ),
    ]
