# Generated by Django 5.1.7 on 2025-05-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_contactinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
